- name: Update existing packages
  community.general.pacman:
    update_cache: true
    upgrade: true

- name: Install basic dependencies
  community.general.pacman:
    state: present
    name: "{{ basics_packages }}"

- name: Look up the target user
  ansible.builtin.getent:
    database: passwd
    key: "{{ play_user }}"

- name: Check if yay is installed
  ansible.builtin.command: /usr/bin/pacman -Qq yay yay-bin yay-git
  register: basics_yay_is_installed
  changed_when: false
  failed_when: basics_yay_is_installed.rc not in [0, 1]
  check_mode: false

- name: Install yay
  ansible.builtin.include_tasks: yay.yml
  when:
    - basics_yay_is_installed.stdout_lines | length == 0
    - not ansible_check_mode

- name: Add hostname as entry for /etc/hosts (this fixes some bugs including https://github.com/flatpak/flatpak/issues/4194)
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1\s+'
    line: "127.0.1.1        {{ ansible_facts['hostname'] }}"
    state: present

- name: Setup systemd units
  ansible.builtin.include_tasks: systemd.yml
