- name: Create the `aur_builder` group
  ansible.builtin.group:
    name: aur_builder

- name: Create the `aur_builder` user
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: aur_builder

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/11-install-aur_builder
    content: "aur_builder ALL=(root) NOPASSWD: /usr/bin/pacman\n"
    owner: root
    group: root
    mode: "0440"
    validate: '/usr/bin/visudo -cf %s'
