- name: Install hyprland & dependencies
  community.general.pacman:
    state: present
    name:
      - hyprland
      - hyprpicker

- name: Create hypr config folder
  ansible.builtin.file:
    path: "{{ play_user_config_dir }}/hypr"
    mode: "{{ perm_folders }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
    state: directory

- name: Copy lua scripts
  ansible.builtin.copy:
    backup: true
    src: "{{ item }}"
    dest: "{{ play_user_config_dir }}/hypr/{{ item }}"
    mode: "0644"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
  loop: "{{ _hyprland_config_files }}"

- name: Copy .luarc.json
  ansible.builtin.copy:
    backup: true
    src: .luarc.json
    dest: "{{ play_user_config_dir }}/hypr/.luarc.json"
    mode: "0644"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"

- name: Copy xdph.conf
  ansible.builtin.copy:
    backup: true
    src: xdph.conf
    dest: "{{ play_user_config_dir }}/hypr/xdph.conf"
    mode: "0644"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"

- name: Check if overrides script exists
  ansible.builtin.stat:
    path: "{{ play_user_config_dir }}/hypr/overrides.lua"
  register: hyprland_overrides

- name: Ensure override script exists
  ansible.builtin.file:
    dest: "{{ play_user_config_dir }}/hypr/overrides.lua"
    mode: "{{ perm_files }}"
    state: touch
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
  when: not hyprland_overrides.stat.exists

- name: Copy scripts folder
  ansible.builtin.copy:
    backup: true
    src: scripts/
    dest: "{{ play_user_config_dir }}/hypr/scripts"
    mode: "{{ perm_folders }}"
    owner: "{{ play_user }}"
    group: "{{ play_user }}"
