- name: Install PCI detection tools
  community.general.pacman:
    name: pciutils
    state: present

- name: Detect NVIDIA GPU
  ansible.builtin.command: lspci -nn
  register: nvidia_lspci_out
  changed_when: false
  check_mode: false

- name: Install nvidia drivers and tools
  community.general.pacman:
    state: present
    name:
      - nvidia-open
      - nvidia-utils
      - nvidia-settings
      - nvtop
      - libva-nvidia-driver
  when: nvidia_lspci_out.stdout is search('(?m)^[^\n]*\[03[0-9a-f]{2}\]:[^\n]*\[10de:')
