# A random suffix is added so builds never reuse a shared directory.
basics_yay_build_dir: /tmp/yay

basics_packages:
  - git
  - base-devel
  - acl
  - openssh

basics_systemd_enable_user:
  - ssh-agent.service

basics_systemd_enable_system: []
